data-path="data" 
genesis-file="../cliqueGenesis.json" 
network-id = 1337 
rpc-http-enabled = true
rpc-http-api=["ETH","NET","CLIQUE", "WEB3", "ADMIN"] 
#host-allowlist="*" 
rpc-http-cors-origins=["all"]
profile="ENTERPRISE"
data-storage-format = "FOREST"